# Multi-stage image for mailroom
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.

FROM python:3.12-slim AS build
WORKDIR /app
# Install dependencies *before* copying the source tree so this expensive
# layer (dagster + friends) is reused by Docker layer caching / the buildx
# registry cache unless pyproject.toml or requirements.txt change. A minimal
# placeholder package satisfies the build so `pip install .` resolves deps.
COPY README.md pyproject.toml requirements.txt* ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && mkdir -p src/mailroom && touch src/mailroom/__init__.py \
    && /opt/venv/bin/pip install --no-cache-dir .
# Now copy the real source and reinstall the package itself. Deps are already
# in the venv, so this layer is cheap (rebuilds on every source change only).
COPY . .
RUN /opt/venv/bin/pip install --no-cache-dir --no-deps .

FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD curl -fsS http://127.0.0.1:3003/server_info || exit 1
# BUG-3 fixes (memos/mailroom-deploy-bugs): dagster dev needs the module
# (-m mailroom.definitions — no [tool.dagster] block exists) and DAGSTER_HOME
# must exist before boot (it's a mount at runtime, so mkdir in the entry).
CMD ["sh","-c","mkdir -p ${DAGSTER_HOME:-/data/dagster} && exec dagster dev -h 0.0.0.0 -p 3003 -m mailroom.definitions"]
