# Multi-stage image for mailroom
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.

FROM python:3.12-slim AS build
WORKDIR /app
COPY requirements.txt* pyproject.toml* ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip
COPY . .
RUN if [ -f requirements.txt ]; then /opt/venv/bin/pip install --no-cache-dir -r requirements.txt; else /opt/venv/bin/pip install --no-cache-dir .; fi

FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD curl -fsS http://127.0.0.1:3003/server_info || exit 1
# BUG-3 fixes (memos/mailroom-deploy-bugs): dagster dev needs the module
# (-m mailroom.definitions — no [tool.dagster] block exists) and DAGSTER_HOME
# must exist before boot (it's a mount at runtime, so mkdir in the entry).
CMD ["sh","-c","mkdir -p ${DAGSTER_HOME:-/data/dagster} && exec dagster dev -h 0.0.0.0 -p 3003 -m mailroom.definitions"]
