[project]
name = "mailroom"
version = "0.1.0"
description = "A mailroom project generated with genproj"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster",
    "dagster-webserver",
    "httpx",
    "dagster",
    "dagster-webserver"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.16.3"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
src = ["src", "tests"]
